name = "WaterLilyMeshBodies"
uuid = "634e6054-d510-4276-b3a3-6481ab5b18dc"
authors = ["Gabriel Weymouth <gabriel.weymouth@gmail.com>"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
